demo/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.number_list_create, name='number_list_create'),
    path('number_list_create', views.number_list_create, name='number_list_create'),
    path('previous_demos', views.previous_demos, name='previous_demos'),
    path('sorting_list/<current>', views.sorting_list, name='sorting_list'),
    path('sorting_list/<current>/sort/<s>', views.sort, name='sort'),
]

library_db/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from portfolio import settings
from . import views

urlpatterns = [
    path('', views.login_view, name='login'),
    path('login', views.login_view, name='login'),
    path('signup', views.initial_signup_view, name='signup'),
    path('logout', LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),
    path('library_admin_login', views.admin_login_view, name='library_admin_login'),
    path('library_admin_page', views.admin_page, name='library_admin_page'),
    path('addtional_info', views.additional_info, name='additional_info'),
    path('book_list', views.book_list, name='book_list'),
    path('book_detail/<book>', views.book_detail, name='book_detail'),
    path('make_librarian/<user>', views.make_librarian, name='make_librarian'),
    path('delete_librarian/<librarian>', views.delete_librarian, name='delete_librarian'),
    path('insert_book', views.insert_book, name='insert_book'),
    path('book_copies/<book>', views.book_copies, name='book_copies'),
    path('add_new_copy/<book>', views.add_new_copy, name='add_new_copy'),
    path('delete_copy/<book>/<copy>', views.delete_copy, name='delete_copy'),
    path('librarian_book_list', views.librarian_book_list, name='librarian_book_list'),
    path('checkout/<copy>', views.checkout, name='checkout'),
    path('checkin/<checked>', views.checkin, name='checkin'),
    path('history_list', views.history_list, name='history_list'),
    path('history_detail/<current>', views.history_detail, name='history_detail')
]

portfolio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import demo.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('demo.urls')),
    path('demo/', include(('demo.urls', 'demo'), namespace='demo')),
    path('about', demo.views.about, name='about'),
    path('library_db/', include(('library_db.urls', 'library_db'), namespace='library_db')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

library_db/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class LibraryUser(models.Model):
    STATUS_TYPES = (
        ('excellent', 'excellent'),
        ('good', 'good'),
        ('probationary', 'probationary'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    birthdate = models.DateField()
    status = models.CharField(max_length=20, choices=STATUS_TYPES, default='good')

    def __str__(self):
        return self.user.username


class Librarian(models.Model):
    librarian_id = models.ForeignKey(LibraryUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.librarian_id.user.username


class LibraryAdmin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=50)

    def __str__(self):
        return self.username


class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    publisher = models.CharField(max_length=100)
    publish_date = models.DateField()
    number_of_pages = models.IntegerField()

    def __str__(self):
        return self.title + ' written by ' + self.author

    class Meta:
        unique_together = (('title', 'author'),)


class BookCopy(models.Model):
    book_key = models.ForeignKey(Book, on_delete=models.CASCADE)
    copy_number = models.IntegerField()
    book_in = models.BooleanField(default=True)

    def __str__(self):
        if self.book_in:
            return str(self.book_key) + ' copy ' + str(self.copy_number) + ' is in'
        else:
            return str(self.book_key) + ' copy ' + str(self.copy_number) + ' is out'

    class Meta:
        unique_together = (('book_key', 'copy_number'),)


class Checkout(models.Model):
    user_id = models.ForeignKey(LibraryUser, on_delete=models.DO_NOTHING)
    librarian_id = models.ForeignKey(Librarian, on_delete=models.DO_NOTHING)
    book_copy = models.ForeignKey(BookCopy, on_delete=models.DO_NOTHING)
    date_of_checkout = models.DateTimeField()
    due_date = models.DateField()

    def __str__(self):
        return str(self.user_id) + ' checked out ' + str(self.book_copy) + ' with ' + str(self.librarian_id) + ' on ' + \
               str(self.date_of_checkout) + ' and it is due on ' + str(self.due_date)


class History(models.Model):
    checkout = models.OneToOneField(Checkout, on_delete=models.DO_NOTHING)
    date_of_checkin = models.DateTimeField(default=None, blank=True, null=True)

    def __str__(self):
        if self.date_of_checkin is not None:
            return str(self.checkout) + ' and was returned on ' + str(self.date_of_checkin)
        else:
            return str(self.checkout)

library_db/forms.py
from django import forms
from . import models


class CreateLibraryUser(forms.ModelForm):
    class Meta:
        model = models.LibraryUser
        fields = ['first_name', 'last_name', 'birthdate']


class CreateBook(forms.ModelForm):
    class Meta:
        model = models.Book
        fields = ['title', 'author', 'publisher', 'publish_date', 'number_of_pages']

library_db/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, authenticate
from .models import LibraryAdmin, LibraryUser, Librarian, Book, BookCopy, Checkout, History
from . import forms


def book_list(request):
    books = Book.objects.all().order_by('author', 'title')
    return render(request, 'library_db/book_list.html', {'books': books})


def librarian_book_list(request):
    user = request.user
    librarians = Librarian.objects.all()
    users = LibraryUser.objects.exclude(librarian__in=librarians)
    if user not in users:
        books = Book.objects.all().order_by('author', 'title')
        return render(request, 'library_db/librarian_book_list.html', {'books': books})
    else:
        return redirect('library_db:login')


@login_required(login_url='library_db/login/')
def book_detail(request, book):
    book = list(book.split(" written by "))
    b = Book.objects.get(title=book[0], author=book[1])
    copies = BookCopy.objects.filter(book_key=b)
    user = LibraryUser.objects.get(user__username=request.user)
    #histories = History.objects.get(checkout__user_id=user, date_of_checkin=None)
    check_outs = Checkout.objects.filter(user_id=user, book_copy__book_in=False, history__date_of_checkin=None)
    return render(request, 'library_db/book_detail.html', {'copies': copies, 'book': b, 'out_copies': check_outs})


def insert_book(request):
    user = request.user
    librarians = Librarian.objects.all()
    users = LibraryUser.objects.exclude(librarian__in=librarians)
    if user not in users:
        if request.method == 'POST':
            form = forms.CreateBook(request.POST)
            if form.is_valid():
                book = form.save()
                return redirect('library_db:book_copies', book=book)
        else:
            form = forms.CreateBook()
            return render(request, 'library_db/book_creation.html', {'form': form})
    else:
        return redirect('library_db:login')


def initial_signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('library_db:additional_info')
    else:
        form = UserCreationForm()
    return render(request, 'library_db/signup.html', {'form': form})


def additional_info(request):
    if request.method == 'POST':
        birth_string = request.POST['birthdate']
        birth_list = birth_string.split('/')
        birthdate = datetime.date(int(birth_list[2]), int(birth_list[0]), int(birth_list[1]))
        try:
            form = LibraryUser.objects.create(user_id=request.user.id, user=request.user,
                                              first_name=request.POST['first_name'],
                                              last_name=request.POST['last_name'],
                                              birthdate=birthdate)
        except IntegrityError:
            form = forms.CreateLibraryUser()
            render(request, 'library_db/additional_info.html', {'form': form})
        form.save()
        return redirect('library_db:book_list')
    else:
        form = forms.CreateLibraryUser()
    return render(request, 'library_db/additional_info.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            return redirect('library_db:book_list')
    else:
        form = AuthenticationForm()
    return render(request, 'library_db/login.html', {'form': form})


def admin_login_view(request):
    error_message = ''
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        try:
            admin = LibraryAdmin.objects.get(username=username, password=password)
        except LibraryAdmin.DoesNotExist:
            admin = None
        if admin is not None:
            user = authenticate(request, username='admin', password='librariesarecool')
            login(request, user)
            return redirect('library_db:library_admin_page')
        else:
            error_message = 'Wrong username or password'
    return render(request, 'library_db/library_admin_login.html', {'error_message': error_message})


def admin_page(request):
    if request.user.username == 'admin':
        librarians = Librarian.objects.all()
        users = LibraryUser.objects.exclude(librarian__in=librarians)
        return render(request, 'library_db/library_admin_page.html', {'librarians': librarians, 'users': users})
    else:
        return redirect('library_db:library_admin_login')


def make_librarian(request, user):
    if request.method == 'POST':
        u = LibraryUser.objects.filter(user__username=user)
        Librarian.objects.create(librarian_id=u[0]).save()
    return redirect('library_db:library_admin_page')


def delete_librarian(request, librarian):
    if request.method == 'POST':
        l = LibraryUser.objects.filter(user__username=librarian)
        Librarian.objects.filter(librarian_id=l[0]).delete()
    return redirect('library_db:library_admin_page')


def book_copies(request, book):
    user = request.user
    librarians = Librarian.objects.all()
    users = LibraryUser.objects.exclude(librarian__in=librarians)
    if user not in users:
        book = list(book.split(" written by "))
        b = Book.objects.get(title=book[0], author=book[1])
        copies = BookCopy.objects.filter(book_key=b)
        return render(request, 'library_db/book_copies.html', {'copies': copies, 'book': b})
    else:
        return redirect('library_db:login')


def add_new_copy(request, book):
    if request.method == 'POST':
        book = list(book.split(" written by "))
        b = Book.objects.get(title=book[0], author=book[1])
        last = BookCopy.objects.filter(book_key=b).order_by('copy_number').last()
        if last is None:
            BookCopy.objects.create(book_key=b, copy_number=1).save()
        else:
            BookCopy.objects.create(book_key=b, copy_number=last.copy_number + 1).save()
    return redirect('library_db:book_copies', book=b)


def delete_copy(request, book, copy):
    if request.method == 'POST':
        book = list(book.split(" written by "))
        copy = list(copy.split(" copy "))
        b = Book.objects.get(title=book[0], author=book[1])
        BookCopy.objects.get(book_key=b, copy_number=copy[1][0]).delete()
    return redirect('library_db:book_copies', book=b)


def checkout(request, copy):
    user = LibraryUser.objects.get(user=request.user)
    number_of_weeks = datetime.timedelta(days=14)
    due_date = datetime.date.today() + number_of_weeks
    # get user status
    # good equals 2 weeks
    # excellent 4 weeks
    # probationary 1 week
    if request.method == 'POST':
        l = LibraryUser.objects.get(user__username=request.POST['librarian'])
        librarian = Librarian.objects.get(librarian_id=l)
        copy = list(copy.split(" copy "))
        copy_number = copy[1][0]
        b = list(copy[0].split(" written by "))
        book = Book.objects.get(title=b[0], author=b[1])
        c = BookCopy.objects.get(book_key=book, copy_number=copy_number)
        c.book_in = False
        c.save()
        ch = Checkout.objects.create(user_id=user, librarian_id=librarian, book_copy=c,
                                     date_of_checkout=datetime.datetime.now(), due_date=due_date)
        ch.save()
        History.objects.create(checkout=ch).save()
        return redirect('library_db:history_detail', current=ch)
    librarians = Librarian.objects.all()
    return render(request, 'library_db/checkout.html', {'librarians': librarians, 'copy': copy, 'due_date': due_date})


def checkin(request, checked):
    user = LibraryUser.objects.get(user__username=request.user)
    checked = list(checked.split(' copy '))
    date = checked[1]
    date = list(date.split(' and '))
    date_of_checkout = list(date[0].split(' on '))[1]
    due_date = list(date[1].split(' on '))[1]
    copy_number = checked[1][0]
    checked = list(checked[0].split(' out '))
    checked = list(checked[1].split(' written by '))
    title = checked[0]
    author = checked[1]
    book = Book.objects.get(title=title, author=author)
    copy = BookCopy.objects.get(book_key=book, copy_number=copy_number)
    ch = Checkout.objects.get(user_id=user, book_copy=copy, date_of_checkout=date_of_checkout, due_date=due_date,
                              book_copy__book_in=False)
    copy.book_in = True
    copy.save()
    check_in = History.objects.get(checkout=ch)
    check_in.date_of_checkin = datetime.datetime.now()
    check_in.save()
    return redirect('library_db:book_list')


def history_list(request):
    user = request.user
    librarians = Librarian.objects.all()
    users = LibraryUser.objects.exclude(librarian__in=librarians)
    if user not in users:
        histories = History.objects.all().order_by('checkout__date_of_checkout')
        return render(request, 'library_db/history_list.html', {'histories': histories})
    else:
        return redirect('library_db:login')


def history_detail(request, current):
    return render(request, 'library_db/history_detail.html', {'checkout': current})

library_db/templates/library_db/additional_info.html
{% extends 'library_db/library_db_layout.html' %}
{% block librarycontent %}
    <h1>Signup</h1>
    <form class="sit-form" action="{% url 'library_db:additional_info' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type = "submit" value="Signup">
    </form>
{% endblock %}

library_db/templates/library_db/book_copies.html
{% extends 'library_db/library_db_layout.html' %}
{% block librarycontent %}
    <h1>Book Copies</h1>
    <h2>Click on one to remove it from circulation</h2>
    <div class="copies">
        {% for copy in copies %}
            <div class="copies">
                <form class="nav-link active" action="{% url 'library_db:delete_copy' book copy %}" method="post">
                    {% csrf_token %}
                    <button type="submit">{{ copy }}</button>
                </form>
            </div>
        {% endfor %}
    </div>
    <h2>Click the below button to add a new book</h2>
    <form class="nav_link active" action="{% url 'library_db:add_new_copy' book %}" method="post">
        {% csrf_token %}
        <button type="submit">+</button>
    </form>
    <h4><a href="{% url 'library_db:librarian_book_list' %}">Back To Book List</a></h4>
{% endblock %}

library_db/templates/library_db/book_creation.html
{% extends 'library_db/library_db_layout.html' %}
{% block librarycontent %}
    <div class="create-book">
        <h2>Add New Book</h2>
        <form class="site-form" action="{% url 'library_db:insert_book' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>
{% endblock %}

library_db/templates/library_db/book_detail.html
{% extends 'library_db/library_db_layout.html' %}
{% block librarycontent %}
    <h1>Book Detail</h1>
    <h2>Title: {{ book.title }}</h2>
    <h2>Author: {{ book.author }}</h2>
    <h2>Published by: {{ book.publisher }}</h2>
    <h2>Published on: {{ book.publish_date }}</h2>
    <h2>Number of Pages: {{ book.number_of_pages }}</h2>
    <h1>Book Copies</h1>
    <div class="copies">
        {% for copy in copies %}
            <div class="d">
            {% if copy.book_in %}
                <h2><a href="{% url 'library_db:checkout' copy %}">{{ copy }}</a></h2>
            {% endif %}
            </div>
        {% endfor %}
    </div>
    {% if out_copies is not None %}
        <h2>Would you like to check in any of the following?</h2>
        {% for out_copy in out_copies %}
            <h3><a href="{% url 'library_db:checkin' out_copy %}">{{ out_copy }}</a></h3>
        {% endfor %}
    {% endif %}
    <h4><a href="{% url 'library_db:book_list' %}">Back To Book List</a></h4>
{% endblock %}

library_db/templates/library_db/book_list.html
{% extends 'library_db/library_db_layout.html' %}
{% block librarycontent %}
    <h1>Book List</h1>
    <div class="books">
        {% for book in books %}
            <div class="d">
                <h2><a href="{% url 'library_db:book_detail' book %}">{{ book.title }} by {{ book.author }}</a></h2>
            </div>
        {% endfor %}
    </div>
{% endblock %}

library_db/templates/library_db/checkout.html
{% extends 'library_db/library_db_layout.html' %}
{% block librarycontent %}
    <h1>Would you like to check out {{ copy }}?</h1>
    <h2>It will be due on {{ due_date }}</h2>
    <form class="site_form" action="{% url 'library_db:checkout' copy %}" method="post">
        {% csrf_token %}
        <label for="librarian">Please select a Librarian:</label>
        <select name="librarian" id="librarian">
            {% for librarian in librarians %}
                <option value="{{ librarian }}">{{ librarian }}</option>
            {% endfor %}
        </select>
        <br>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

library_db/templates/library_db/history_detail.html
{% extends 'library_db/library_db_layout.html' %}
{% block librarycontent %}
    <h1>We love testing</h1>
{% endblock %}

library_db/templates/library_db/history_list.html
{% extends 'library_db/library_db_layout.html' %}
{% block librarycontent %}
    <h1>History List</h1>
    <div class="histories">
        {% for history in histories %}
            <div class="d">
                <h2><a href="{% url 'library_db:history_detail' history.checkout %}">{{ history }}</a></h2>
            </div>
        {% endfor %}
    </div>
{% endblock %}

library_db/templates/library_db/librarian_book_list.html
{% extends 'library_db/library_db_layout.html' %}
{% block librarycontent %}
    <h1>Book List</h1>
    <div class="books">
        {% for book in books %}
            <div class="d">
                <h2><a href="{% url 'library_db:book_copies' book %}">{{ book.title }} by {{ book.author }}</a></h2>
            </div>
        {% endfor %}
    </div>
{% endblock %}

library_db/templates/library_db/library_admin_login.html
{% extends 'library_db/library_db_layout.html' %}
{% block librarycontent %}
    <h1>Admin Login</h1>
    <form class="sit-form" action="{% url 'library_db:library_admin_login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username:</label><br>
        <input type="text" id="username" name="username"><br>
        <label for="password">Password:</label><br>
        <input type="password" id="password" name="password"><br>
        <input type="submit" value="Login">
    </form>
    <p>{{ error_message }}</p>
{% endblock %}

library_db/templates/library_db/library_admin_page.html
{% extends 'library_db/library_db_layout.html' %}
{% block librarycontent %}
    <h3>Please be kind when demoing and only mess with a user you have created</h3>
    <h1>Users</h1>
    <h2>Click on one to make them a librarian</h2>
    <div class="users">
        {% for user in users %}
            <div class="user">
                <form class="nav-link active" action="{% url 'library_db:make_librarian' user %}" method="post">
                    {% csrf_token %}
                    <button type="submit">{{ user.first_name }} {{ user.last_name }}</button>
                </form>
            </div>
        {% endfor %}
    </div>
    <h1>Librarians</h1>
    <h2>Click on one to demote them to regular user status</h2>
    <div class="librarians">
        {% for librarian in librarians %}
            <div class="librarian">
                <form class="nav-link active" action="{% url 'library_db:delete_librarian' librarian %}" method="post">
                    {% csrf_token %}
                    <button type="submit">{{ librarian.librarian_id.first_name }} {{ librarian.librarian_id.last_name }}
                    </button>
                </form>
            </div>
        {% endfor %}
    </div>
{% endblock %}

library_db/templates/library_db/library_db_layout.html
{% extends 'base_layout.html' %}
{% block content %}
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'about' %}">About</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'demo:number_list_create' %}">Demo</a>
        </li>
        <li class="nav-item">
            <a class="nav-link disabled" href="#">Game (Still Working on It)</a>
        </li>
        <li class="nav-item">
            <a class="nav-link disabled" href="#">AI/ML Schtuff (yeah... Still Working on It)</a>
        </li>
    </ul>
    <ul>
        {% if user.is_authenticated %}
            <li>
                <form class="logout-link" action="{% url 'library_db:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Logout</button>
                </form>
            </li>
        {% else %}
            <li>
                <a href="{% url 'library_db:login' %}">Login</a>
            </li>
            <li>
                <a href="{% url 'library_db:signup' %}">Signup</a>
            </li>
        {% endif %}
    </ul>
    {% block librarycontent %}
    {% endblock %}
{% endblock %}

library_db/templates/library_db/login.html
{% extends 'library_db/library_db_layout.html' %}
{% block librarycontent %}
    <h1>Login</h1>
    <form class="sit-form" action="{% url 'library_db:login'%}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <input type = "submit" value="Login">
    </form>
{% endblock %}

library_db/templates/library_db/signup.html
{% extends 'library_db/library_db_layout.html' %}
{% block librarycontent %}
    <h1>Signup</h1>
    <form class="sit-form" action="{% url 'library_db:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type = "submit" value="Signup">
    </form>
{% endblock %}