demo/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.number_list_create, name='number_list_create'),
    path('number_list_create', views.number_list_create, name='number_list_create'),
    path('previous_demos', views.previous_demos, name='previous_demos'),
    path('sorting_list/<current>', views.sorting_list, name='sorting_list'),
    path('sorting_list/<current>/sort/<s>', views.sort, name='sort'),
]

library_db/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from portfolio import settings
from . import views

urlpatterns = [
    path('', views.login_view, name='login'),
    path('login', views.login_view, name='login'),
    path('signup', views.initial_signup_view, name='signup'),
    path('logout', LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),
    path('library_admin_login', views.admin_login_view, name='library_admin_login'),
    path('library_admin_page', views.admin_page, name='library_admin_page'),
    path('addtional_info', views.additional_info, name='additional_info'),
    path('book_list', views.book_list, name='book_list'),
    path('book_detail/<book>', views.book_detail, name='book_detail'),
    path('make_librarian/<user>', views.make_librarian, name='make_librarian'),
    path('delete_librarian/<librarian>', views.delete_librarian, name='delete_librarian'),
    path('insert_book', views.insert_book, name='insert_book'),
    path('book_copies/<book>', views.book_copies, name='book_copies'),
    path('add_new_copy/<book>', views.add_new_copy, name='add_new_copy'),
    path('delete_copy/<book>/<copy>', views.delete_copy, name='delete_copy'),
    path('librarian_book_list', views.librarian_book_list, name='librarian_book_list'),
    path('checkout/<copy>', views.checkout, name='checkout'),
    path('checkin/<checked>', views.checkin, name='checkin'),
    path('history_list', views.history_list, name='history_list'),
    path('history_detail/<current>', views.history_detail, name='history_detail')
]

portfolio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import demo.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('demo.urls')),
    path('demo/', include(('demo.urls', 'demo'), namespace='demo')),
    path('about', demo.views.about, name='about'),
    path('library_db/', include(('library_db.urls', 'library_db'), namespace='library_db')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/about.html
{% extends 'base_layout.html' %}
{% load static from static %}
{% block content %}
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'demo:number_list_create' %}">Demo</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'library_db:book_list' %}">Database</a>
        </li>
        <li class="nav-item">
            <a class="nav-link disabled" href="#">Game (Still Working on It)</a>
        </li>
        <li class="nav-item">
            <a class="nav-link disabled" href="#">AI/ML Schtuff (yeah... Still Working on It)</a>
        </li>
    </ul>
    <h1>About Me</h1>
    <object data="{% static 'Resume.pdf' %}"
            type="application/pdf"
            width="100%"
            height="700px"></object>
{% endblock %}

templates/base_layout.html
{%  load static from static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Portfolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{%  static 'styles.css' %}">
</head>
<body>
<div class="container">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>